{% set version = "1.4.17" %}

package:
  name: m4
  version: {{ version }}

source:
  fn: m4-{{ version }}.tar.gz  # [not win]
  url: http://ftp.gnu.org/gnu/m4/m4-{{ version }}.tar.gz  # [not win]
  sha256: 3ce725133ee552b8b4baca7837fb772940b25e81b2a9dc92537aeaf733538c9e  # [not win]
  fn: m4-{{ version }}.tar.xz  # [win]
  url: http://mirrors.kernel.org/sourceware/cygwin/x86_64/release/m4/m4-{{ version }}-2.tar.xz  # [win]
  sha256: 016f2a5f79f04deb8d3f1b47e28e01659c3c1f8611e40db9d8f312617f34b2ff  # [win]
  

build:
  number: 1

requirements:
  build:
    - posix  # [win]
    - m2w64-toolchain  # [win]
  run:
    - posix  # [win]
    - m2w64-gcc-libs   # [win]
    - m2-msys2-runtime  # [win]
  
test:
  commands:
    - m4 --help
    - m4 --version
    - conda inspect linkages -p $PREFIX m4  # [not win]
    - conda inspect objects -p $PREFIX m4  # [osx]

about:
  home: http://www.gnu.org/software/m4/
  license: GPL-3.0
  license_file: COPYING  # [not win]
  license_file: share\doc\m4\COPYING  # [win]
  summary: 'Implementation of the traditional Unix macro processor.'

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
