{% set version = "1.4.20" %}

package:
  name: m4
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/m4/m4-{{ version }}.tar.gz
  sha256: 6ac4fc31ce440debe63987c2ebbf9d7b6634e67a7c3279257dc7361de8bdb3ef
  patches:
    # From Homebrew: https://raw.githubusercontent.com/macports/macports-ports/edf0ee1e2cf/devel/m4/files/secure_snprintf.patch
    - secure_snprintf.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libtool
    - make

test:
  commands:
    - m4 --help
    - m4 --version

about:
  home: http://www.gnu.org/software/m4/
  license: GPL-3.0
  license_file: COPYING
  summary: 'Implementation of the traditional Unix macro processor.'

  description: |
    GNU M4 is an implementation of the traditional Unix macro processor. It is
    mostly SVR4 compatible although it has some extensions (for example,
    handling more than 9 positional parameters to macros). GNU M4 also has
    built-in functions for including files, running shell commands, doing
    arithmetic, etc.
  doc_url: http://www.gnu.org/software/m4/manual/index.html
  dev_url: http://git.savannah.gnu.org/gitweb/?p=m4.git

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid
