schema_version: 1

context:
  version: "1.4.21"

package:
  name: m4
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/m4/m4-${{ version }}.tar.gz
  sha256: 38ae59f7a30bf9c108193cc5c25fbb06014f21e230c7ede2eff614f7b7c37ed8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - libtool
    - make

tests:
  - script:
      - m4 --help
      - m4 --version

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Implementation of the traditional Unix macro processor.
  description: |
    GNU M4 is an implementation of the traditional Unix macro processor. It is
    mostly SVR4 compatible although it has some extensions (for example,
    handling more than 9 positional parameters to macros). GNU M4 also has
    built-in functions for including files, running shell commands, doing
    arithmetic, etc.
  homepage: https://www.gnu.org/software/m4/
  repository: https://git.savannah.gnu.org/gitweb/?p=m4.git
  documentation: https://www.gnu.org/software/m4/manual/index.html

extra:
  recipe-maintainers:
    - ocefpaf
    - mingwandroid
    - xhochy
