appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: VntS9UUZeJh5A8qiwU0/egA6J5PoifrxuBKPfxEg/Oog7U+GUav1H6SXCOrcMZ0BUYfLxOYj71OPU1L5UDKPaRdkbsUSvQDcqW8Rh3lzE9UT4u/iQuWWYfG0M3zZyH6gNpQkIWgaRAshKPMzi6hSTFEWwvJED8GZPvmZwgm3UYktENl+n/GVJYXLquMoCdL/Z2z0tFvJ2iucNnVaceM4DZEq4LJy7IcVrW0khk/fzjQZkrekbtQ5pHgxUKOBdmM2U1WftdzjEBlukkDa5yfRsTzuIK/6vpyhspvH3okDUFIhkjH4WowqWTqKDzJFbCurjb9hZLaTOxI6362XBh3K3DT4wW7YQ7pAGYyQQK5FneN4YAq8uzoka5gXD3vM7hFIDc383sprEHNp6T4+sYl6H+pCqRP2HmdCGBlm+FGsdSIkaOYGJW809n7fOnfV5mz3pkhrsJiI1RNPXlgg+90o1ydVR1K3ZjO0keVnsJa+V/q/4CBqJaD757IMjji3z6/Q0F14CgZdWmrPU6oMo8gxA+s7gp2ys5tYqrvfaKfgS/aIdfKRbfoXDjMbK7p8fAgaKI10cqU88efMx108OOOpPdEwCzVpj4XoCiiUdGymTAMjErSICis/RZnajX8+9QCPBR8r99YBkc1QXf7hPrrfwmJJzUvTiBGTGXQioDha8gE=}
